on:
  push:
    branches:
      - 'main'
name: deploy
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.17.0

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install git zip unzip -y
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHubActions BOT"
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          php composer.phar update --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          php composer.phar install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Build the site
        run: npm run prod

      - name: deploy
        run: |
          if [ -d "./docs" ]; then rm -Rf ./docs; fi
          mv ./build_production ./docs
          git add ./docs
          git commit -m "Deployment of website - $(date)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DEPLOY_SECRET }}
          branch: live
          force: true

