on:
  push:
    branches:
      - 'main'
name: deploy
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install PHP and Node
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update && apt upgrade -y
          apt install -y php php-mbstring php-cli php-bcmath php-json php-xml php-zip php-pdo php-common php-tokenizer php-mysql curl git unzip zip
          curl -sL https://deb.nodesource.com/setup_16.x | bash -
          apt install -y nodejs

      - name: Install dependencies
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          php composer.phar update --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          php composer.phar install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Build the site
        run: npm run prod

      - name: Build and deploy
        run: |
          if [ -d "./docs" ]; then rm -Rf ./docs; fi
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHubActions BOT"
          mv ./build_production ./docs
          git checkout -b live
          git add ./docs
          git commit -m "Deployment of website - $(date)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DEPLOY_SECRET }}
          branch: live

